[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  functions = "netlify/functions"
  publish = "build" # Adjust if your build directory is different

[[redirects]]
  from = "/api/reports/*"
  to = "/api/reports/:splat"
  status = 200
  force = true