[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "serverless/"
  publish = "build" # Adjust if your build directory is different

[[redirects]]
  from = "/api/reports/*"
  to = "/api/reports/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lighthouse", "chrome-launcher"]

  [functions.generate-reports]
    memory = 1024
    timeout = 120

[build.environment]
REPORTS_BASE_PATH = "/opt/build/repo"  # This is an example path, adjust as needed