[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  functions = "netlify/functions" # Directory for your functions
  publish = "build" # Your build output directory, adjust if necessary

[[redirects]]
  from = "/api/reports/*"
  to = "/api/reports/:splat"
  status = 200
  force = true