[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "serverless/"
  publish = "build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
