[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  functions = "serverless/"
  publish = "build"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lighthouse", "chrome-launcher"]

[functions.generate-reports]
  memory = 1024
  timeout = 120